import React from "react";
import SideBar from "../incs/SideBar";
import NavBarBootstrap from "../incs/NavBarBootstrap";

const GitIgnore = () => {
  return (
    <>
      <div className="container-fluid position-relative p-0">
        <SideBar />
        <div class="content">
          <NavBarBootstrap />
          <div class="container-fluid px-4">
            <div class="row g-4">
              <div className="col-md-12 mt-5">
                <code>
                  <pre>
                    <p>
                      # Created by
                      https://www.toptal.com/developers/gitignore/api/node
                    </p>
                    <p>
                      # Edit at
                      https://www.toptal.com/developers/gitignore?templates=node
                    </p>
                    <p># Node.gitignore</p>
                    <p>#</p>
                    <p>
                      # This file is generated by
                      https://www.toptal.com/developers/gitignore?templates=node
                    </p>
                    <p>
                      # It is *NOT* recommended to store this file in version
                      control as it
                    </p>
                    <p>
                      # can conflict with other users' configurations on
                      different machines
                    </p>
                    <p>#</p>
                    <p>
                      # https://www.toptal.com/developers/gitignore/api/node
                    </p>
                    <p>#</p>
                    <p># Dependency directories</p>
                    <p>node_modules/</p>
                    <p>jspm_packages/</p>
                    <p>#</p>
                    <p># Testing directories</p>
                    <p>coverage/</p>
                    <p>#</p>
                    <p># Production build directory</p>
                    <p>build/</p>
                    <p>#</p>
                    <p># .env files</p>
                    <p>.env.local</p>
                    <p>.env.*.local</p>
                    <p>.env</p>
                    <p>.env.test</p>
                    <p>.env.production</p>
                    <p>#</p>
                    <p># npm-debug.log*</p>
                    <p>npm-debug.log*</p>
                    <p>#</p>
                    <p># yarn.lock</p>
                    <p>yarn.lock</p>
                    <p>#</p>
                    <p># ESLint cache</p>
                    <p>.eslintcache</p>
                    <p>#</p>
                    <p># IDEs and editors</p>
                    <p>/.idea</p>
                    <p>/.vscode</p>
                    <p>/.project</p>
                    <p>/.classpath</p>
                    <p>/.c9/</p>
                    <p>/.fusebox/</p>
                    <p>/.eclipse/</p>
                    <p>/tmp/</p>
                    <p>/.nyc_output</p>
                    <p>/.webpack/</p>
                    <p>/.serverless/</p>
                    <p>/.parcel/</p>
                    <p>/.cache/</p>
                    <p>/.next/</p>
                    <p>/.nuxt/</p>
                    <p>/.next-server/</p>
                    <p>/.gatsby/</p>
                    <p>/.tern-port</p>
                  </pre>
                </code>
              </div>
            </div>
          </div>
        </div>
        <button class="btn btn-lg btn-lg-square back-to-top">
          <i class="bi bi-arrow-up"></i>
        </button>
      </div>
    </>
  );
};

export default GitIgnore;
